name: Sync Assignment Problems

on:
  push:
    branches: [modify-assignments]
  pull_request:
    branches: [modify-assignments]

env:
  OMEGAUP_API_TOKEN: ${{ secrets.OMEGAUP_API_TOKEN }}
  GIT_USERNAME: ${{ github.actor }}

jobs:
  sync-problems:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository with PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install omegaup

    - name: Run sync script to add/remove problems
      working-directory: utils
      run: |
        python3 sync_assignment_problems.py --api-token $OMEGAUP_API_TOKEN

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff --staged --quiet; then
          echo "✅ No changes to commit"
        else
          git commit -m "🔁 Auto-sync: Updated assignment problems from OmegaUp"
          git push
